services:
  servidor-html:
    container_name: alfonso_svr
    #image: servidor-html
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "C:/Users/integ/Desktop/Rafa Perez Lopez/IFCD0210/MF0493/compose_alfonso:/data"